### PR TITLE
#127: Add missing methods to the Python API

### PR DESCRIPTION
**Pull request by arcturusannamalai**
#127: Add missing methods to the Python API
- add EvalLinearWSum, EvalMultMany, EvalAddManyInPlace, EvalLinearWSumMutable

### CODE REVIEW

**Comment by arcturusannamalai** [comment]
@yspolyakov - I'm not able to create a feature branch on your openfheorg repository; so I can just send a PR/MR. Not sure how you want this to work.

**Comment by yspolyakov** [comment]
Hi @arcturusannamalai It looks your invite has expired, in other words, you have not accepted it. I am going to regenerate the invite. Please accept as it as soon as you see it.

**Comment by yspolyakov** [comment]
I just regenerated the invite

**Comment by arcturusannamalai** [comment]
I accepted it; thank you !

**Pull request closed without merging**
