### PR TITLE
added function to get just the real component from the CKKSPlaintext

### PR DESCRIPTION
**Pull request by IanQS**
Simple code to get back the values as a real vector instead of a complex vector that needs to be converted on the users end

### CODE REVIEW

**Comment by reneroliveira** [comment]
Nice suggestion, I was converting the complex in python, but it's better to have a native solution! Thanks

**Review by reneroliveira — APPROVED** [review]

**Comment by IanQS** [comment]
Should I just merge these changes in then? What's the protocol? Sorry, there's no documentation about contributing to the library, so I'm not sure (we should probably get on that)

**Comment by reneroliveira** [comment]
Actually, the best protocol is to merge into dev first, but since it's something more urgent to the conference, I think it's ok

**Comment by IanQS** [comment]
🎉

**Pull request merged**
